[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mist"
version = "0.0.1"
description = "Metabolite Inference with Spectrum Transformers"
readme = "README.md"
authors = [
  { name = "Samuel Goldman" }
]

dependencies = [
  "numpy",
  "pandas",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
